### ISSUE TITLE
fatal error: m_pd.h: No such file or director

### ISSUE THREAD

**Issue by strk** [essej/aoo#3]
That header doesn't seem to be provided by the only dependency documented in the README:
https://packages.debian.org/sid/amd64/libopus-dev/filelist

**Comment by essej** [comment]
Are you trying to build in a different branch? PD is not a requirement, but if your build is configured to use it, then it is. If your interest is via SonoBus, note that SonoBus does NOT use any of the build systems in this repository, it includes only the code it needs.

**Comment by strk** [comment]
I'm trying to build a pure AOO server for use on a system which doesn't even have an audio card.
Is that possible to do with a full SonoBus process ?

**Comment by essej** [comment]
To build an AOO connection server for use with SonoBus you want this repo instead:
  https://github.com/essej/aooserver

Sorry for the confusion... if you want some interactive help, join the discord group: https://discord.gg/wm28tQdYTb and we can figure out what you really need...

**Comment by strk** [comment]
On Wed, Feb 08, 2023 at 09:40:19AM -0800, Jesse Chappell wrote:
> To build an AOO server for use with SonoBus you want this repo instead:
>   https://github.com/essej/aooserver

Thanks, I'm no my way now :)
